# Generated by Django 3.1.2 on 2020-10-22 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentchapter',
            name='feedback',
        ),
        migrations.CreateModel(
            name='StudentChapterFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=255, null=True)),
                ('student_chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chapters.studentchapter')),
            ],
        ),
    ]
