# Generated by Django 3.1.2 on 2020-10-22 12:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0002_auto_20201022_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentchapterfeedback',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 22, 20, 6, 31, 853979)),
        ),
        migrations.AlterField(
            model_name='studentchapter',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chapters.chapter'),
        ),
        migrations.AlterField(
            model_name='studentchapterfeedback',
            name='feedback',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studentchapterfeedback',
            name='student_chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chapters.chapter'),
        ),
    ]
