# Generated by Django 3.1.2 on 2020-10-22 12:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chapters', '0004_auto_20201022_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=255)),
                ('date_posted', models.DateTimeField(default=datetime.datetime(2020, 10, 22, 20, 36, 19, 920074))),
                ('student_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chapters.chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='StudentChapterFeedback',
        ),
    ]
