# Generated by Django 3.1.2 on 2020-10-22 12:43

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chapters', '0005_auto_20201022_2036'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentChapter',
            new_name='StudentRemarks',
        ),
        migrations.AlterField(
            model_name='chapterfeedback',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 22, 20, 43, 16, 503653)),
        ),
    ]
