# Generated by Django 3.1.2 on 2020-11-02 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0007_auto_20201022_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterfeedback',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 2, 17, 38, 59, 229461)),
        ),
    ]
