# Generated by Django 3.1.2 on 2020-11-10 04:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0008_auto_20201102_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterfeedback',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 10, 4, 24, 27, 645457)),
        ),
    ]
