# Generated by Django 3.1.2 on 2020-11-11 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0010_auto_20201110_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterfeedback',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 16, 27, 28, 785349)),
        ),
    ]
