# Generated by Django 3.1.2 on 2020-11-11 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0011_auto_20201111_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterfeedback',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 16, 42, 50, 175061)),
        ),
    ]
