# Generated by Django 3.1.2 on 2020-11-11 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0012_auto_20201111_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterfeedback',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 17, 2, 21, 187372)),
        ),
    ]
