# Generated by Django 3.1.2 on 2020-11-12 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0018_auto_20201112_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterfeedback',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 16, 26, 40, 121445)),
        ),
    ]
