# Generated by Django 3.1.2 on 2020-11-12 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0020_auto_20201112_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterfeedback',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 18, 3, 13, 458718)),
        ),
    ]
