# Generated by Django 3.1.2 on 2020-11-12 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0021_auto_20201112_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterfeedback',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 18, 8, 26, 188150)),
        ),
    ]
