# Generated by Django 3.1.2 on 2020-11-12 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0024_auto_20201112_1857'),
        ('chapters', '0022_auto_20201112_1808'),
    ]

    operations = [
    ]
