# Generated by Django 3.1.2 on 2020-11-16 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0027_auto_20201115_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterfeedback',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 16, 16, 56, 51, 900347)),
        ),
    ]
