# Generated by Django 3.1.2 on 2020-11-22 04:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0033_auto_20201119_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterfeedback',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 4, 29, 59, 871236)),
        ),
    ]
