# Generated by Django 3.1.2 on 2020-11-22 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0035_auto_20201122_0519'),
        ('chapters', '0035_auto_20201122_0915'),
    ]

    operations = [
    ]
