# Generated by Django 3.1.2 on 2020-11-25 02:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0036_merge_20201122_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterfeedback',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 25, 2, 29, 22, 342637)),
        ),
    ]
