# Generated by Django 3.1.2 on 2020-11-12 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choices',
            name='answer_key',
        ),
        migrations.CreateModel(
            name='AnswerKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100, null=True)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='question.question', unique=True)),
            ],
        ),
    ]
