# Generated by Django 3.1.2 on 2020-11-12 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_auto_20201112_1623'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='choices',
            unique_together={('question', 'description')},
        ),
    ]
