# Generated by Django 3.1.2 on 2020-11-12 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_submitanswer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubmitAnswer',
        ),
    ]
