# Generated by Django 3.1.2 on 2020-11-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0008_delete_submitanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='AnswerKey',
        ),
    ]
