# Generated by Django 3.1.2 on 2020-11-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0010_question_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='table_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='q_type',
            field=models.CharField(choices=[('IDENT', 'Identification'), ('MULT', 'Mutliple Choice'), ('TABLE', 'Fill up table'), ('CODE', 'Upload file')], max_length=10),
        ),
    ]
