# Generated by Django 3.1.2 on 2020-11-11 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_studentsection'),
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SetProfActivity',
            new_name='ProfActivity',
        ),
    ]
