# Generated by Django 3.1.2 on 2020-10-17 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20201017_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 17, 14, 49, 4, 11331), null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 17, 14, 49, 4, 11331), null=True),
        ),
    ]
