# Generated by Django 3.1.2 on 2020-10-15 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20201016_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 16, 0, 34, 22, 34824), null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 16, 0, 34, 22, 34824), null=True),
        ),
    ]
