# Generated by Django 3.1.2 on 2020-11-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20201111_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profactivity',
            name='end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='profactivity',
            name='start',
            field=models.DateField(null=True),
        ),
    ]
