# Generated by Django 3.1.2 on 2020-10-16 05:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20201016_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 16, 13, 24, 8, 938508), null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 16, 13, 24, 8, 938508), null=True),
        ),
    ]
