# Generated by Django 3.1.2 on 2020-11-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20201111_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='total_score',
            field=models.IntegerField(null=True),
        ),
    ]
