# Generated by Django 3.1.2 on 2020-11-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_studentsection'),
        ('activity', '0004_activity_total_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='profactivity',
            unique_together={('activity', 'section')},
        ),
    ]
