# Generated by Django 3.1.2 on 2020-10-19 05:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_auto_20201019_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 19, 13, 23, 35, 174244), null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 19, 13, 23, 35, 174244), null=True),
        ),
    ]
