# Generated by Django 3.1.2 on 2020-11-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_studentsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
