# Generated by Django 3.1.2 on 2020-11-15 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubmitAnswer',
        ),
    ]
