# Generated by Django 3.1.2 on 2020-11-22 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assesment', '0001_initial'),
        ('student', '0003_submitsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitsummary',
            name='assesment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assesment.assesment'),
        ),
    ]
