# Generated by Django 3.1.2 on 2020-11-25 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_submitsummary_assesment'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitsummary',
            name='remarks',
            field=models.BooleanField(default=True),
        ),
    ]
