# Generated by Django 3.1.2 on 2020-12-01 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_submitsummary_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitsummary',
            name='points',
            field=models.IntegerField(null=True),
        ),
    ]
